# Generated by Django 5.0.1 on 2024-03-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_messege_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_and_quantity_total',
            field=models.IntegerField(default=0),
        ),
    ]
