# Generated by Django 5.0.1 on 2024-03-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_order_customer_remove_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discounted_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
