# Generated by Django 5.0.1 on 2024-03-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_products_discounted_price_products_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discounted_price',
            field=models.IntegerField(default=1),
        ),
    ]
